global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:8888']

  - job_name: 'mimir'
    static_configs:
      - targets: ['mimir:9009']

  # OpenTelemetry Collector metrics endpoint
  - job_name: 'opentelemetry-metrics'
    static_configs:
      - targets: ['otel-collector:8889']
    honor_labels: true
    metrics_path: /metrics

  # Node Exporter metrics (if you add node-exporter later)
  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']

remote_write:
  - url: http://mimir:9009/api/v1/push
    send_exemplars: true

alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # AlertManager can be added here when needed
      # - alertmanager:9093
